# Generated by Django 3.2.9 on 2021-11-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20211115_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variation',
            new_name='product',
        ),
    ]
