# Generated by Django 3.2.9 on 2021-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=[(0, 's'), (1, 'm'), (2, 'l'), (3, 'xl'), (4, 'xxl')]),
        ),
    ]
