# Generated by Django 3.2.9 on 2021-11-14 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20211115_0119'),
        ('product', '0004_alter_productvariation_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interact',
            new_name='Action',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
